/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITestOracle__factory } from './ITestOracle__factory'
export { LepakCore__factory } from './LepakCore__factory'
