/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type { ITestOracle, ITestOracleInterface } from '../../LepakCore.sol/ITestOracle'

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: '_asset',
        type: 'address',
      },
    ],
    name: 'priceOfERC20',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'priceOfETH',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
]

export class ITestOracle__factory {
  static readonly abi = _abi
  static createInterface(): ITestOracleInterface {
    return new utils.Interface(_abi) as ITestOracleInterface
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ITestOracle {
    return new Contract(address, _abi, signerOrProvider) as ITestOracle
  }
}
