/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type { ILepakCore, ILepakCoreInterface } from '../../Interfaces/ILepakCore'

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: '_user',
        type: 'address',
      },
    ],
    name: 'isMember',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_mod',
        type: 'address',
      },
    ],
    name: 'isMod',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
]

export class ILepakCore__factory {
  static readonly abi = _abi
  static createInterface(): ILepakCoreInterface {
    return new utils.Interface(_abi) as ILepakCoreInterface
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ILepakCore {
    return new Contract(address, _abi, signerOrProvider) as ILepakCore
  }
}
