/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type { FunctionFragment, Result } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from '../common'

export interface ITestOracleInterface extends utils.Interface {
  functions: {
    'priceOfERC20(address)': FunctionFragment
    'priceOfETH()': FunctionFragment
  }

  getFunction(nameOrSignatureOrTopic: 'priceOfERC20' | 'priceOfETH'): FunctionFragment

  encodeFunctionData(functionFragment: 'priceOfERC20', values: [PromiseOrValue<string>]): string
  encodeFunctionData(functionFragment: 'priceOfETH', values?: undefined): string

  decodeFunctionResult(functionFragment: 'priceOfERC20', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'priceOfETH', data: BytesLike): Result

  events: {}
}

export interface ITestOracle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: ITestOracleInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    priceOfERC20(_asset: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[BigNumber]>

    priceOfETH(overrides?: CallOverrides): Promise<[BigNumber]>
  }

  priceOfERC20(_asset: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>

  priceOfETH(overrides?: CallOverrides): Promise<BigNumber>

  callStatic: {
    priceOfERC20(_asset: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>

    priceOfETH(overrides?: CallOverrides): Promise<BigNumber>
  }

  filters: {}

  estimateGas: {
    priceOfERC20(_asset: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>

    priceOfETH(overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    priceOfERC20(
      _asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    priceOfETH(overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
