/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type { ITellorOracle, ITellorOracleInterface } from '../../LepakMembership.sol/ITellorOracle'

const _abi = [
  {
    inputs: [],
    name: 'getCurrentEthPrice',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'pure',
    type: 'function',
  },
]

export class ITellorOracle__factory {
  static readonly abi = _abi
  static createInterface(): ITellorOracleInterface {
    return new utils.Interface(_abi) as ITellorOracleInterface
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ITellorOracle {
    return new Contract(address, _abi, signerOrProvider) as ITellorOracle
  }
}
