/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type { ILepakLifestyle, ILepakLifestyleInterface } from '../ILepakLifestyle'

const _abi = [
  {
    inputs: [],
    name: 'addStay',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'applyForStay',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'idx',
        type: 'uint256',
      },
    ],
    name: 'getStay',
    outputs: [
      {
        components: [
          {
            internalType: 'address',
            name: 'addr',
            type: 'address',
          },
          {
            internalType: 'uint256',
            name: 'dateJoined',
            type: 'uint256',
          },
        ],
        internalType: 'struct ILepakLifestyle.LepakStay',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'removeStay',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'reviewForStay',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'whitelistForStay',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
]

export class ILepakLifestyle__factory {
  static readonly abi = _abi
  static createInterface(): ILepakLifestyleInterface {
    return new utils.Interface(_abi) as ILepakLifestyleInterface
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ILepakLifestyle {
    return new Contract(address, _abi, signerOrProvider) as ILepakLifestyle
  }
}
